export const theme = {
    color: {
        yellow: '#ffff4c',
        green: '#ACECA1',
        orange: '#FBB02D',
        pink: '#fe65b7',
        blue: '#446DF6',
        purple: '#AB87FF',
        white: '#ffffff',
        light: '#EFEFEF',
        medium: '#8F8F8F',
        dark: '#333333',
    },
    elementSizes: {
        na: 0,
        xs: 8,
        sm: 16,
        md: 24,
        lg: 32,
        xl: 40,
    },
    typographySizes: {
        h1: 100,
        h2: 80,
        h3: 35,
        h4: 20,
        p: 12,
        a: 12,
        li: 12,
    },
};
